# MySQL (default setup).  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# And be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
# SCOTT THIS IS NOT USED... JUST NEED DUMMARY DATABASE

<% require 'socket' %>
<% hostname_val = Socket.gethostname %>
# <% my_host_flag = hostname_val =='svbalance.cure.com.ph'%> 
# <% my_host_flag = hostname_val=='oliver-ficonab-com.local' if !my_host_flag %>
#<% my_host_flag = hostname_val=='amontpellier-257-1-113-107.w90-0.abo.wanadoo.fr' %>
<% my_host_flag = hostname_val!='svbalance.cure.com.ph' %>

<% dbname = my_host_flag ? 'smsapp_development' : 'smsapp_production' %>
<% dbhost= my_host_flag ? 'localhost' : 'dbmysql.cure.com.ph' %>
<% the_env = my_host_flag ? 'development:' : 'production:' %>
<% puts "DBCONFIG: hostname #{hostname_val} dbname #{dbname} hostflag #{my_host_flag} env #{the_env} dbhost #{dbhost}" %>

development:
  adapter: jdbcmysql
  database: <%= dbname %>
  username: <%= my_host_flag ? 'root' : 'scott' %>  
  password: <%= my_host_flag ? 'Abby789' : 'scott' %> 
  encoding: utf8
  host: <%= my_host_flag ? 'localhost' : 'dbmysql.cure.com.ph' %>

production:
  adapter: jdbc
  jndi: jdbc/smsapp
  driver: com.mysql.jdbc.Driver 

#  socket: <%= my_host_flag ? '/opt/local/var/run/mysql5/mysqld.sock' :  '/var/lib/mysql/mysql.sock' %>  
# Warning: The database defined as 'test' will be erased and
# re-generated from your development database when you run 'rake'.
# Do not set this db to the same as development or production.
test:
  adapter: mysql
  database: smsapp_test
  username: root
  password: Abby789
  host: localhost
  encoding: utf8

#production: